### ISSUE TITLE
Arguments to dependencies

### ISSUE THREAD

**Issue by hasn-prevas** [134130/intellij-mise#194]
With the following mise.toml:

```toml
[tasks.echo]
run = "echo"

[tasks.hello-world]
depends = ["echo 'Hello World'"]
```

I get an error saying "Cannot resolve symbol 'echo 'Hello World''. The plugin should ignore arguments to dependencies when resolving tasks.
